### ISSUE TITLE
Error canner init:schema

### ISSUE THREAD

**Issue by overpod** [CannerCMS/cannercms#30]
``` bash
~/projects/test$ canner init:schema
```
#### Error
``` bash
module.js:549
    throw err;
    ^

Error: Cannot find module 'lodash.mapValues'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@canner/cli/lib/data.js:15:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@canner/cli/lib/index.js:6:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

```

**Comment by abz53378** [comment]
Hi, @overpod, thanks for reporting the bug, it was caused by case sensitivity and we fix it in `@canner/cli@2.2.2`.

Please upgrade `@canner/cli` and try it again. Thanks!
